"use client";

import { useState } from "react";
import {
  Camera,
  Sparkles,
  CheckCircle2,
  X,
  Copy,
  Check,
  Share2,
  SunMedium,
  Palette,
  Package,
  Layers
} from "lucide-react";

import { Button } from "@/components/ui/button";

type AiShotlistModalProps = {
  isOpen: boolean;
  onClose: () => void;
  job: {
    title: string;
    shootType: string;
    clientName?: string | null;
    location?: string | null;
    concept?: string | null;
  };
};

const SHOTLIST_PRESETS: Record<string, {
  mustHaves: string[];
  candid: string[];
  details: string[];
  wardrobe: string[];
  lighting: string;
  gear: string[];
}> = {
  graduation: {
    mustHaves: [
      "Pose berdiri tegak pegang map ijazah / tabung toga",
      "Pose setengah badan (portrait) senyum anggun / gagah",
      "Foto bertiga bersama orang tua (ayah kanan, ibu kiri, wisudawan tengah)",
      "Foto wisudawan dirangkul hangat oleh kedua orang tua",
      "Aksi lempar toga bersama ke udara (shutter speed min 1/1000s)"
    ],
    candid: [
      "Tawa lepas candid saat ngobrol santai bareng teman / keluarga",
      "Foto berjalan santai menoleh ke arah kamera",
      "Momen orang tua merapikan toga / selempang wisudawan"
    ],
    details: [
      "Close-up detail nama & gelar pada selempang (sash)",
      "Detail buket bunga & boneka wisuda",
      "Detail medali kelulusan & cincin di jari"
    ],
    wardrobe: ["Kebaya / Jas Modern", "Earthy Sage & Cream", "Broken White & Terracotta", "Muted Navy"],
    lighting: "Outdoor Golden Hour: 07.30 - 09.30 WIB atau 15.30 - 17.00 WIB. Gunakan backlight untuk rim light pada jubah toga.",
    gear: ["Lensa 85mm f/1.4 (Portrait bokeh tajam)", "Lensa 35mm f/1.8 (Wide foto bersama)", "Reflector 5-in-1", "Baterai cadangan 2x"]
  },
  prewedding: {
    mustHaves: [
      "Pose tatap-tatapan romantis (eye-contact) jarak dekat",
      "Pose berpegangan tangan sambil berjalan perlahan",
      "Pose pelukan dari belakang (back-hug) lembut",
      "Pose duduk berdampingan di bangku / padang rumput"
    ],
    candid: [
      "Candid tertawa lepas karena guyonan pasangan",
      "Pria memakaikan jaket / merapikan rambut wanita",
      "Langkah kaki berkejaran kecil santai"
    ],
    details: [
      "Close-up cincin tunangan di atas bunga",
      "Detail genggaman tangan intim",
      "Detail siluet pasangan saat matahari terbenam"
    ],
    wardrobe: ["Casual Earth Tone", "Dress Putih / Kemeja Linen", "Pastel Soft Blue & Beige"],
    lighting: "Sunset Golden Hour (16.30 - 17.45 WIB). Manfaatkan flare matahari alami.",
    gear: ["Lensa 50mm f/1.2 / f/1.8", "Lensa 24-70mm f/2.8", "ND Filter untuk outdoor terik", "Prism efek kreatif"]
  },
  wedding: {
    mustHaves: [
      "Akad / Pemberkatan: Momen ijab kabul & tukar cincin",
      "Foto formal pengantin di pelaminan bersama keluarga inti",
      "Foto cium tangan suami & kecup kening istri",
      "Foto berdua di lorong dekorasi bunga"
    ],
    candid: [
      "Air mata haru saat sungkeman ke orang tua",
      "Tawa pengantin saat teman-teman teriak heboh",
      "MUA touch up riasan pengantin di ruang rias"
    ],
    details: [
      "Gaun pengantin digantung & sepatu wedding",
      "Buku nikah & mahar / seserahan",
      "Detail henna / cincin kawin di atas mahar"
    ],
    wardrobe: ["Baju Adat Tradisional / Gaun Internasional"],
    lighting: "Indoor Flash TTL / Godox V1 on-camera bounce ceiling + Softbox off-camera untuk pelaminan.",
    gear: ["2x Bodi Kamera (Dual slot card)", "Lensa 24-70mm f/2.8", "Lensa 70-200mm f/2.8", "2x Flash Eksternal"]
  }
};

export function AiShotlistModal({ isOpen, onClose, job }: AiShotlistModalProps) {
  const [copied, setCopied] = useState(false);
  const typeKey = job.shootType in SHOTLIST_PRESETS ? job.shootType : "graduation";
  const preset = SHOTLIST_PRESETS[typeKey] || SHOTLIST_PRESETS.graduation;

  if (!isOpen) return null;

  const fullText = `📋 *SHOTLIST & MOODBOARD GUIDE: ${job.title.toUpperCase()}*
📍 Lokasi: ${job.location || "Lokasi Pemotretan"}
🎓 Kategori: ${job.shootType.toUpperCase()}

📸 *FOTO WAJIB (MUST-HAVE)*:
${preset.mustHaves.map((s, i) => `${i + 1}. ${s}`).join("\n")}

🎭 *CANDID & EMOSIONAL*:
${preset.candid.map((s, i) => `• ${s}`).join("\n")}

🔍 *DETAIL SHOTS*:
${preset.details.map((s, i) => `• ${s}`).join("\n")}

🎨 *REKOMENDASI WARNA*: ${preset.wardrobe.join(", ")}
⏰ *TIPS PENCAHAYAAN*: ${preset.lighting}
🎒 *GEAR CHECKLIST*: ${preset.gear.join(" • ")}

_Generated by KalaVisual AI_`;

  const handleCopy = () => {
    navigator.clipboard.writeText(fullText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fade-in">
      <div className="relative w-full max-w-2xl overflow-hidden rounded-2xl border border-border bg-card shadow-2xl animate-scale-up flex flex-col max-h-[85vh]">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-border/80 px-5 py-4 bg-gradient-to-r from-violet-500/10 via-emerald-500/10 to-transparent">
          <div className="flex items-center gap-3">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-violet-600 text-white shadow-md shadow-violet-500/20">
              <Camera className="h-5 w-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-base font-bold tracking-tight text-foreground">
                  AI Shotlist & Moodboard Guide
                </h2>
                <span className="rounded-full bg-violet-500/15 px-2 py-0.5 text-[10px] font-semibold text-violet-700 dark:text-violet-300 capitalize">
                  {job.shootType} Shoot
                </span>
              </div>
              <p className="text-xs text-muted-foreground">
                Panduan pose wajib, ide candid, rekomendasi warna, dan gear lapangan.
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg p-1.5 text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Content */}
        <div className="p-5 space-y-4 overflow-y-auto">
          {/* Must Have Shots */}
          <div className="rounded-xl border border-border/80 bg-muted/20 p-4 space-y-2">
            <h4 className="text-xs font-bold text-foreground flex items-center gap-1.5 text-emerald-700 dark:text-emerald-300">
              <CheckCircle2 className="h-4 w-4" /> Pose Wajib Lapangan (Must-Have Checklist)
            </h4>
            <div className="space-y-1.5 pt-1">
              {preset.mustHaves.map((shot, idx) => (
                <label key={idx} className="flex items-start gap-2.5 text-xs text-foreground cursor-pointer group">
                  <input type="checkbox" className="mt-0.5 rounded border-border text-emerald-600 focus:ring-emerald-500" />
                  <span className="group-hover:text-emerald-700 transition-colors">{shot}</span>
                </label>
              ))}
            </div>
          </div>

          {/* Candid & Details Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {/* Candid */}
            <div className="rounded-xl border border-border/80 bg-muted/20 p-3.5 space-y-2">
              <h4 className="text-xs font-bold text-foreground flex items-center gap-1.5 text-cyan-700 dark:text-cyan-300">
                <Sparkles className="h-3.5 w-3.5" /> Momen Candid & Emosional
              </h4>
              <ul className="space-y-1 text-xs text-muted-foreground list-disc list-inside">
                {preset.candid.map((c, i) => (
                  <li key={i}>{c}</li>
                ))}
              </ul>
            </div>

            {/* Details */}
            <div className="rounded-xl border border-border/80 bg-muted/20 p-3.5 space-y-2">
              <h4 className="text-xs font-bold text-foreground flex items-center gap-1.5 text-amber-700 dark:text-amber-300">
                <Layers className="h-3.5 w-3.5" /> Detail & Close-Up
              </h4>
              <ul className="space-y-1 text-xs text-muted-foreground list-disc list-inside">
                {preset.details.map((d, i) => (
                  <li key={i}>{d}</li>
                ))}
              </ul>
            </div>
          </div>

          {/* Color & Lighting */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div className="rounded-xl border border-border/80 bg-muted/20 p-3.5 space-y-1.5">
              <h4 className="text-xs font-bold text-foreground flex items-center gap-1.5 text-pink-700 dark:text-pink-300">
                <Palette className="h-3.5 w-3.5" /> Rekomendasi Palet Warna
              </h4>
              <div className="flex flex-wrap gap-1.5 pt-1">
                {preset.wardrobe.map((w, i) => (
                  <span key={i} className="rounded-md bg-pink-100 dark:bg-pink-950/50 px-2 py-0.5 text-[11px] font-medium text-pink-700 dark:text-pink-300">
                    {w}
                  </span>
                ))}
              </div>
            </div>

            <div className="rounded-xl border border-border/80 bg-muted/20 p-3.5 space-y-1.5">
              <h4 className="text-xs font-bold text-foreground flex items-center gap-1.5 text-amber-700 dark:text-amber-300">
                <SunMedium className="h-3.5 w-3.5" /> Tips Pencahayaan
              </h4>
              <p className="text-xs text-muted-foreground leading-relaxed">{preset.lighting}</p>
            </div>
          </div>

          {/* Gear Checklist */}
          <div className="rounded-xl border border-border/80 bg-gradient-to-r from-violet-500/5 to-cyan-500/5 p-3.5 space-y-1.5">
            <h4 className="text-xs font-bold text-foreground flex items-center gap-1.5">
              <Package className="h-3.5 w-3.5 text-violet-600" /> Checklist Alat Lapangan
            </h4>
            <p className="text-xs text-muted-foreground">{preset.gear.join(" • ")}</p>
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between border-t border-border px-5 py-3.5 bg-muted/20">
          <Button variant="ghost" size="sm" onClick={onClose}>
            Tutup
          </Button>

          <Button
            size="sm"
            onClick={handleCopy}
            className="bg-violet-600 hover:bg-violet-700 text-white shadow-sm flex items-center gap-1.5"
          >
            {copied ? (
              <>
                <Check className="h-3.5 w-3.5 text-emerald-300" />
                Tersalin ke Clipboard!
              </>
            ) : (
              <>
                <Copy className="h-3.5 w-3.5" />
                Salin Shotlist untuk WhatsApp
              </>
            )}
          </Button>
        </div>
      </div>
    </div>
  );
}
